"""adding spiceness

Revision ID: dc3d31b16660
Revises: 59a2db502263
Create Date: 2020-08-26 17:37:03.271962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc3d31b16660"
down_revision = "59a2db502263"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rating", sa.Column("spiciness", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rating", "spiciness")
    # ### end Alembic commands ###
