"""empty message

Revision ID: f6df6c335898
Revises: 7378a2ba5b88
Create Date: 2020-09-29 16:53:23.494441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6df6c335898"
down_revision = "7378a2ba5b88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rating", sa.Column("date", sa.Integer(), nullable=True))
    op.add_column("rating", sa.Column("rate_by", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rating", "rate_by")
    op.drop_column("rating", "date")
    # ### end Alembic commands ###
